# Generated by Django 3.0.4 on 2020-03-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Leads',
        ),
    ]
